# Generated by Django 3.2.13 on 2022-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
