# Generated by Django 3.2.13 on 2022-04-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(error_messages={'required': 'This field is required'}, max_length=50)),
                ('last_name', models.CharField(error_messages={'required': 'This field is required'}, max_length=50)),
                ('email', models.EmailField(error_messages={'required': 'This field is required'}, max_length=100, unique=True)),
                ('username', models.CharField(error_messages={'required': 'This field is required'}, max_length=50, unique=True)),
                ('phone_no', models.CharField(error_messages={'required': 'This field is required'}, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
