# Generated by Django 3.2.13 on 2022-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.PositiveIntegerField(),
        ),
    ]
