# Generated by Django 3.2.13 on 2022-05-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_address_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
    ]
