# Generated by Django 3.2.13 on 2022-05-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_address_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
