# Generated by Django 3.2.13 on 2022-05-28 04:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
