# Generated by Django 3.2.13 on 2022-05-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
