# Generated by Django 3.2.13 on 2022-05-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderproduct_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='address',
        ),
    ]
