# Generated by Django 3.2.13 on 2022-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220512_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
