# Generated by Django 3.2.13 on 2022-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220513_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='device',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=20, null=True),
        ),
    ]
