# Generated by Django 3.2.13 on 2022-04-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/banners')),
                ('subtitle', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
