# Generated by Django 3.2.13 on 2022-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20220426_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
