# Generated by Django 3.2.13 on 2022-04-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_alter_banner_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
