# Generated by Django 3.2.13 on 2022-04-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_alter_banner_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
